version: '3'
services:
  api:
    container_name: "api"
    build: ./docker/uvicorn
    restart: always
    tty: true
    ports:
      - 8100:8000
    volumes:
      - ./api:/usr/src/api
  web:
    container_name: "web"
    build: ./docker/node
    restart: always
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app